Features/smhi root
Ingenjorsarbete-For-Klimatet/ifk-smhi pull request #35
Opened 2022-11-26 18:52 UTC by docNord

I figure it is time to merge this into main now, to keep the pull request reasonably sized.

Quite a lot of functionality added:

* Finding closest station to given latitude and longitude
* Finding stations within given radius of given latitude and longitude
* Finding stations in vicinity of city, either closest or within given radius

On top of that, umbrella function for getting data has been added. Also, data format from Metobs has been changed to datetime to accomodate using diff() when building interpolation strategies.

I figure it is best to merge this back into main before developing further. Next step is to look at interpolation strategies and include mesan and strång functionality. Also, both unit and integration tests need to be added / updated.

Example to show one means by which I plan to include interpolation: Looking at nearby stations. When evaluating the snow depth around Kiruna, data is available starting from the late 19th century. Some stations lack data for extended periods in time, however. We can address the problem by looking at all stations around the city by running something like this code snippet:

```
import matplotlib.pyplot as plt
from smhi.smhi import SMHI

client = SMHI()
client.get_stations(3) # Causes error if not run. BUG!
client.find_stations_by_city(8,'Kiruna',20)

for nearby_station in client.nearby_stations:
    header, data = client.get_data(8,nearby_station[0])
    plt.plot(data['datetime'],data['Snödjup'])
plt.show()
```
![snödjup_runt_kiruna](https://user-images.githubusercontent.com/20903303/204104570-19b71d3e-3df3-4f10-b01a-e5c9174946b7.png)

2022-11-27 09:47 UTC, mgcth requested changes
Nice additions! I think we should address unit and integration tests here, along with docs showing how to use these newly added features.

2022-11-27 09:47 UTC, mgcth commented on src/smhi/metobs.py
> +        table["datetime"] = table["Datum"] + ' ' + table["Tid (UTC)"]
Looks good, but I guess both integration and unit tests need to be updated.

2022-11-27 09:47 UTC, mgcth commented on src/smhi/smhi.py
> +            stations = [
I would consider simplifying this or rewriting it as a normal loop. A bit hard to follow complex (multi-line) list comprehensions.

2022-11-27 09:47 UTC, mgcth commented on src/smhi/smhi.py
> +            self.nearby_stations = [
Same here.

I think updating the unit tests will show how this method could be simplified.

2022-11-27 09:47 UTC, mgcth commented on src/smhi/smhi.py
> +            city: name of city
Same order as method parameters.

2022-11-27 09:47 UTC, mgcth commented on src/smhi/smhi.py
> +
Linting error (no new line here).

2022-11-27 09:47 UTC, mgcth commented on src/smhi/smhi.py
> +    ) -> None:
This method returns a tuple of something (is it str and some sort of list)? Strange that mypy doesn't fail here.

2023-01-22 09:13 UTC, docNord commented
@mgcth could you help me resolve this?

2023-01-24 22:09 UTC, mgcth commented
Is functionality done but missing tests?

2023-01-25 04:41 UTC, docNord commented
I will fix it after work today. Functionality was done but I started over
to fix black and lint and tests, require some hours. You will have a PR to
review tonight 😊

On Tue, 24 Jan 2023, 23:09 Mladen Gibanica, ***@***.***>
wrote:

> Is functionality done but missing tests?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi/pull/35#issuecomment-1402757403>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE7PLB5CVZQGRD4TUMRZVPLWUBHJTANCNFSM6AAAAAASMD2QRI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-01-29 09:15 UTC, docNord commented
Alright, the smhi feature works for Metobs. Should we incorporate fast access to the other subcategories as well?

Example:

```
from smhi.smhi import SMHI
s = SMHI()
s.find_stations_by_city(8,'Kiruna')
s.nearby_stations
h1,d1 = s.get_data(8,180960)
_ ,d2 = s.get_data(8,180960,interpolate=40)
``` 

![Kiruna_snödjup](https://user-images.githubusercontent.com/20903303/215316749-3e1b7610-b811-4ce7-8074-078ec93a317a.png)

2023-01-29 09:56 UTC, docNord commented
Metfcts would also benefit from functionality similar to the Metobs wrapper functions just developed, and I am sure Mesan and Strang as well - it will be very succint if you can ask our SMHI client for data from a named place and get it automatically.

How do we go about setting this up? @mgcth you have a parallell branch to align data output formats from the different modules, once that is in place it should be doable to align with minor adjustments.

2023-01-29 11:39 UTC, mgcth commented
> Metfcts would also benefit from functionality similar to the Metobs wrapper functions just developed, and I am sure Mesan and Strang as well - it will be very succint if you can ask our SMHI client for data from a named place and get it automatically.
> 
> How do we go about setting this up? @mgcth you have a parallell branch to align data output formats from the different modules, once that is in place it should be doable to align with minor adjustments.

Create an issue about it, and we can talk more about design there.

2023-01-31 18:23 UTC, mgcth commented on src/smhi/smhi.py
> +
```suggestion

```
Fix linting.

2023-02-02 06:29 UTC, mgcth commented
Haven't had the time to look at it. Will try this afternoon.

2023-02-04 10:17 UTC, mgcth approved these changes
If you agree with the exception, this can be merged.

2023-02-04 10:21 UTC, mgcth commented
maybe you want to fix the `latin1` and `utf-8` encoding of the fixture file before merging. Also, do the docs need updating?

2023-02-04 10:26 UTC, docNord commented
I don't know about the fixture file - why should we change it? The docs probably need editing, I could have a look quickly if you like.

2023-02-04 10:27 UTC, mgcth commented
Because `latin1` encoding fails on your win machine... Let's fix it later.

2023-02-04 10:30 UTC, docNord commented
Right - but why can't we just use utf8 as the encoding in the test? That works on my windows machine, is it causing problems on your side?

2023-02-04 10:31 UTC, docNord commented
Also, looking at the docs: I'm thinking adding an example page for smhi would be good? Otherwise, I don't know where to add the stuff we've been working at here...

2023-02-04 18:32 UTC, mgcth commented
@docNord, can you try running tests from the latest commit on your local computer?

2023-02-04 21:57 UTC, docNord commented
The new variant works on my Windows machine too. Great work Mladen! With that, ok to merge? Will create a new PR, hopefully tomorrow, for adding place search to the other protocols.

2023-02-04 21:58 UTC, merged